### ISSUE TITLE
Промежуточная обратная связь по заданию 1

### ISSUE THREAD

**Issue by bss-git** [annieareyouokay/Lesson1#1]
Привет. Решил накидать ос по коду, что есть.
Классно, что вынес переиспользуемые методы в отдельную сборку.
В целом всё классно, мне нравится.

---

https://github.com/annieareyouokay/Lesson1/blob/b46943421f07f2efc8956f8860384ef7ca067515/Utilities/Auxiliary.cs#L19
Обычно мы не используем ключевые слова ref и readonly в сигнатуре метода.
Массив - ссылочный тип и всегда передаётся в метод как ссылка на массив в памяти. Элементы массива при этом можно будет изменить внутри метода. ref предназначен скорее для передачи в метод тяжёлых структур (значимых типов), чтобы сэкономить ресурсы на их копировании.

---

https://github.com/annieareyouokay/Lesson1/blob/b46943421f07f2efc8956f8860384ef7ca067515/Utilities/Auxiliary.cs#L24
Для соединения элементов с разделителем можно использовать метод String.Join https://learn.microsoft.com/ru-ru/dotnet/api/system.string.join?view=net-8.0

---

https://github.com/annieareyouokay/Lesson1/blob/b46943421f07f2efc8956f8860384ef7ca067515/ReverseArray/Program.cs#L9
По нашим соглашениям мы всегда используем var для объявления переменной, это никак не влияет на работу кода, но экономит место и убирает шум. Очень актуально, когда используются длинные имена типов.

---

https://github.com/annieareyouokay/Lesson1/blob/b46943421f07f2efc8956f8860384ef7ca067515/MinAvg/Program.cs#L24
Метод возвращает целое число, что часто будет не соответствовать среднему значению. Можно использовать например тип double.

---

https://github.com/annieareyouokay/Lesson1/blob/b46943421f07f2efc8956f8860384ef7ca067515/MinAvg/Program.cs#L11
https://github.com/annieareyouokay/Lesson1/blob/b46943421f07f2efc8956f8860384ef7ca067515/MinAvg/Program.cs#L24
Если бы мы писали код в продакшен, мы бы использовали библиотечные методы
https://learn.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.min?view=net-8.0
https://learn.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.average?view=net-8.0
Это просто для справки, показать, что такие и многие другие есть в стандартной библиотеке.

**Comment by annieareyouokay** [comment]
Спасибо за обратную связь! Внес правки в проект согласно замечаниям
